from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, text
from app.database import get_session
from app.models import Project

router = APIRouter(tags=["export"])


@router.get("/projects/{slug}/export/fastapi", response_class=PlainTextResponse)
async def export_fastapi(slug: str, session: AsyncSession = Depends(get_session)):
    project = await session.scalar(select(Project).where(Project.slug == slug))
    if not project:
        raise HTTPException(404, "Project not found")

    result = await session.execute(text("""
        SELECT DISTINCT res.method, res.path, p.name AS permission_name
        FROM resources res
        JOIN permission_resources pr ON pr.resource_id = res.id
        JOIN permissions p ON p.id = pr.permission_id
        WHERE res.project_id = :pid
        ORDER BY res.path, res.method
    """), {"pid": project.id})
    rows = result.fetchall()

    lines = [
        f"# Generated by RBACExplorer — {project.name}",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from typing import Callable",
        "",
        "router = APIRouter()",
        "",
        "",
        "def require_permission(permission: str) -> Callable:",
        '    """Replace get_current_user_permissions with your own auth logic."""',
        "    def dependency(current_permissions: list[str] = Depends(get_current_user_permissions)):",
        "        if permission not in current_permissions:",
        '            raise HTTPException(status_code=403, detail="Forbidden")',
        "    return dependency",
        "",
        "",
        "# --- Route stubs ---",
        "",
    ]

    for row in rows:
        method = row.method.lower()
        safe_path = row.path.strip("/").replace("/", "_").replace("{", "").replace("}", "")
        func_name = f"{method}_{safe_path}" if safe_path else method
        lines += [
            f'@router.{method}("{row.path}")',
            f'async def {func_name}(_=Depends(require_permission("{row.permission_name}"))):\n    ...',
            "",
        ]

    return "\n".join(lines)
