import yaml
from fastapi import APIRouter
from fastapi.responses import PlainTextResponse
from sqlalchemy import select, text
from sqlalchemy.orm import selectinload

from app.dependencies import CurrentUser, DBSession, get_project_for_user_or_404
from app.models import Role, RoleInheritance, RolePermission

router = APIRouter(tags=["export"])


@router.get("/projects/{slug}/export/fastapi", response_class=PlainTextResponse)
async def export_fastapi(slug: str, current_user: CurrentUser, session: DBSession):
    project = await get_project_for_user_or_404(slug, current_user, session)

    result = await session.execute(
        text("""
        SELECT DISTINCT res.method, res.path, p.name AS permission_name
        FROM resources res
        JOIN permission_resources pr ON pr.resource_id = res.id
        JOIN permissions p ON p.id = pr.permission_id
        WHERE res.project_id = :pid
        ORDER BY res.path, res.method
    """),
        {"pid": project.id},
    )
    rows = result.fetchall()

    lines = [
        f"# Generated by RBACExplorer — {project.name}",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from typing import Callable",
        "",
        "router = APIRouter()",
        "",
        "",
        "def require_permission(permission: str) -> Callable:",
        '    """Replace get_current_user_permissions with your own auth logic."""',
        "    def dependency(",
        "        current_permissions: list[str] = Depends(",
        "            get_current_user_permissions",
        "        ),",
        "    ):",
        "        if permission not in current_permissions:",
        '            raise HTTPException(status_code=403, detail="Forbidden")',
        "    return dependency",
        "",
        "",
        "# --- Route stubs ---",
        "",
    ]

    seen_func_names: dict[str, int] = {}

    for row in rows:
        method = row.method.lower()
        # Sanitize path for function name
        safe_path = (
            row.path.strip("/")
            .replace("/", "_")
            .replace("{", "")
            .replace("}", "")
            .replace("-", "_")
        )
        base_name = f"{method}_{safe_path}" if safe_path else method
        if base_name in seen_func_names:
            seen_func_names[base_name] += 1
            func_name = f"{base_name}_{seen_func_names[base_name]}"
        else:
            seen_func_names[base_name] = 1
            func_name = base_name

        # Escape double quotes in permission name to prevent
        # injection in the generated Python code
        safe_perm = row.permission_name.replace('"', '\\"')

        # Escape backslashes first, then double quotes in path to prevent
        # code injection in the generated Python decorator string (SEC-003)
        safe_decorator_path = row.path.replace("\\", "\\\\").replace('"', '\\"')

        lines += [
            f'@router.{method}("{safe_decorator_path}")',
            f'async def {func_name}(_=Depends(require_permission("{safe_perm}"))):\n'
            "    ...",
            "",
        ]

    return "\n".join(lines)


@router.get("/projects/{slug}/export/yaml", response_class=PlainTextResponse)
async def export_yaml(slug: str, current_user: CurrentUser, session: DBSession):
    project = await get_project_for_user_or_404(slug, current_user, session)

    # Fetch Roles with inheritance and permissions
    roles = await session.scalars(
        select(Role)
        .where(Role.project_id == project.id)
        .options(
            selectinload(Role.parent_links).selectinload(RoleInheritance.parent_role),
            selectinload(Role.permission_links).selectinload(RolePermission.permission),
        )
    )

    export_data = {}

    for r in roles:
        role_config = {}

        # 1. Parents (Include)
        parents = [link.parent_role.name for link in r.parent_links if link.parent_role]
        if parents:
            role_config["include"] = parents

        # 2. Group Permissions by Module
        for link in r.permission_links:
            perm = link.permission
            # Only include if there's a dot separator (Module.Action)
            if "." in perm.name:
                parts = perm.name.split(".", 1)
                module = parts[0]
                action = parts[1]
                if module not in role_config:
                    role_config[module] = {}
                role_config[module][action] = perm.description or ""
            else:
                if "other" not in role_config:
                    role_config["other"] = {}
                role_config["other"][perm.name] = perm.description or ""

        export_data[r.name] = role_config

    return yaml.safe_dump(export_data, sort_keys=False, allow_unicode=True)
